spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 030610CHENyu
    url: jdbc:mysql://localhost:3306/user_center
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
